# Generated by Django 4.1.3 on 2022-11-04 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circleScoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='draw_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 4, 21, 18, 43, 460523, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
