# Generated by Django 4.1.3 on 2022-11-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circleScoreApp', '0006_alter_circle_circularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='artistName',
            new_name='artist_name',
        ),
    ]
