# Generated by Django 4.1.3 on 2022-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circleScoreApp', '0007_rename_artistname_circle_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='circularity',
            field=models.DecimalField(decimal_places=10, max_digits=16),
        ),
    ]
